### ISSUE TITLE
Git рулит

### ISSUE THREAD

**Issue by maxlavr83** [MicrosoftDocs/Contribute.ru-RU#3]
Круто, что можно принимать участие в формировании документации 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Руководство для участников разработки документации Майкрософт. Общие сведения - Contributor Guide](https://docs.microsoft.com/ru-ru/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.ru-ru/blob/live/Contribute/index.md)
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Здравствуйте, @maxlavr83 
Благодарим Вас за отзыв. Мы рады, что работа с нашей документацией соответствует Вашим ожиданиям. 
Надеемся получить от Вас и другие полезные отзывы, которые помогут нам улучшать работу и дальше. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
